### ISSUE TITLE
Attributes are empty when CAS Server redirect

### ISSUE THREAD

**Issue by jjbenitez026** [Observat/dspace6-and-org-jasig-cas-client-v3.4#1]
Hi!
I am trying to configure DSpace JSPUI to authenticate with CAS.
DSpace already redirects me well to the CAS server and returns the ticket and service well, but when you register the new user
` registerNewNetidFromCAS(Context context, HttpServletRequest request, Assertion assertion, String netid)`
the attributes are empty: 
`assertion.getPrincipal ().getAttributes () = []`
What will I be missing?
Thanks in advance and thanks for the work you did.

**Comment by Observat** [comment]
CAS server returns the ticket, service and any other fields.

See settings on CAS server.
